<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-11-15">
<meta name="description" content="Network analysis, community detection, and link prediction on 3,729 artists across 30 festival lineups, to test whether booking structure alone can explain, and predict, who shares a stage.">

<title>Do Festival Lineups Follow a Network? – Shreya Gupta</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shreya Gupta</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">home</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">about</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#building-the-network" id="toc-building-the-network" class="nav-link active" data-scroll-target="#building-the-network">Building the Network</a></li>
  <li><a href="#network-structure-small-world-not-random" id="toc-network-structure-small-world-not-random" class="nav-link" data-scroll-target="#network-structure-small-world-not-random">Network Structure: Small-World, Not Random</a></li>
  <li><a href="#communities-within-the-network" id="toc-communities-within-the-network" class="nav-link" data-scroll-target="#communities-within-the-network">Communities Within the Network</a></li>
  <li><a href="#the-festivals-that-hold-it-together" id="toc-the-festivals-that-hold-it-together" class="nav-link" data-scroll-target="#the-festivals-that-hold-it-together">The Festivals That Hold It Together</a>
  <ul class="collapse">
  <li><a href="#how-far-does-the-reach-of-the-big-three-extend" id="toc-how-far-does-the-reach-of-the-big-three-extend" class="nav-link" data-scroll-target="#how-far-does-the-reach-of-the-big-three-extend">How far does the reach of the big three extend?</a></li>
  </ul></li>
  <li><a href="#testing-the-structure-with-link-prediction" id="toc-testing-the-structure-with-link-prediction" class="nav-link" data-scroll-target="#testing-the-structure-with-link-prediction">Testing the Structure With Link Prediction</a></li>
  <li><a href="#does-the-music-explain-the-communities" id="toc-does-the-music-explain-the-communities" class="nav-link" data-scroll-target="#does-the-music-explain-the-communities">Does the Music Explain the Communities?</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Do Festival Lineups Follow a Network?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">network-analysis</div>
    <div class="quarto-category">music</div>
    <div class="quarto-category">SI-608</div>
  </div>
  </div>

<div>
  <div class="description">
    Network analysis, community detection, and link prediction on 3,729 artists across 30 festival lineups, to test whether booking structure alone can explain, and predict, who shares a stage.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 15, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This project investigates whether the artists who share festival stages form a network with real, measurable structure, structure strong enough to predict who else an artist is likely to play with, and whether that structure is explained by the music itself or by something else entirely. Festival lineups are expensive, high-stakes decisions: promoters spend months assembling artists to balance genre, audience draw, and cost, largely on the strength of relationships and industry intuition rather than data [1]. A co-performance network, where two artists are linked whenever they share a festival bill, offers a way to test that intuition directly. Built from 2023 lineups at 30 U.S. and international festivals and supplemented with Spotify’s track-level audio features, this project asks two questions: does the structure of who-plays-with-whom carry enough signal to predict connections the model hasn’t seen, and can that same structure be explained by what the artists actually sound like?</p>
<section id="building-the-network" class="level2">
<h2 class="anchored" data-anchor-id="building-the-network">Building the Network</h2>
<p>Nodes in the network are individual artists; an edge connects two artists whenever they performed at the same festival, weighted by how many festivals they shared. Lineups came from official festival posters, most of which exist only as promotional images, so artist names were extracted with Google’s Gemini model and manually validated to correct OCR errors and remove hallucinated entries. Artist metadata, danceability, energy, tempo, valence, genre, and popularity, came from a companion Spotify tracks dataset, matched to the network’s artist list.</p>
<p>The resulting graph has 3,729 artists and 507,144 edges. It is a single snapshot of the 2023 festival circuit, and it skews heavily toward electronic dance music: EDM festivals account for roughly 37% of the sample, since most large festivals run a dedicated EDM stage or night even when their overall billing is genre-diverse. That skew matters for how the community-detection results below should be read.</p>
</section>
<section id="network-structure-small-world-not-random" class="level2">
<h2 class="anchored" data-anchor-id="network-structure-small-world-not-random">Network Structure: Small-World, Not Random</h2>
<div id="cell-4" class="cell" data-outputid="0c268652-489a-4e6b-bf7b-b6c29a71a3df" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>{'diameter': 4, 'avg_shortest_path': 2.2830746313835304, 'avg_degree': 272.31536604987934, 'avg_clustering_coeff': 0.9236414851854906}</code></pre>
</div>
</div>
<div id="cell-5" class="cell" data-outputid="ec37f5ae-8b58-4619-c28a-f7797a7fdf14" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>Density: 0.07304596728805776</code></pre>
</div>
</div>
<div id="cell-6" class="cell" data-outputid="b49e2808-a47a-4b4f-eba6-278ee42785b3" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>A diameter of 4 and an average shortest path of 2.28 mean that almost any two of the network’s 3,729 artists are connected through two or three shared festivals, and the clustering coefficient of 0.92 says that artists who share one festival-mate tend to share several more. That combination, short paths and dense local clustering, is the signature of a small-world network.</p>
<p>To check whether that structure was anything more than what density alone would produce, the network was compared against a Watts-Strogatz random-rewiring model matched on node count, edge count, and average degree (Table 1). Even at zero rewiring probability, the Watts-Strogatz model tops out at a clustering coefficient of 0.75, well below the network’s observed 0.92, so the real network is meaningfully more clustered than a comparably-sized lattice. Its assortativity coefficient of 0.313 adds another piece to that picture: well-connected artists tend to co-perform with other well-connected artists, a pattern familiar from real-world collaboration networks such as scientific co-authorship.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Actual network</th>
<th>Watts-Strogatz</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nodes</td>
<td>3,729</td>
<td>3,729</td>
</tr>
<tr class="even">
<td>Edges</td>
<td>507,144</td>
<td>507,732</td>
</tr>
<tr class="odd">
<td>Avg. degree</td>
<td>272.31</td>
<td>272.00</td>
</tr>
<tr class="even">
<td>Clustering coefficient</td>
<td>0.923</td>
<td>0.745</td>
</tr>
<tr class="odd">
<td>Density</td>
<td>0.073</td>
<td>0.073</td>
</tr>
<tr class="even">
<td>Diameter</td>
<td>4</td>
<td>4</td>
</tr>
<tr class="odd">
<td>Avg. path length</td>
<td>2.28</td>
<td>2.75</td>
</tr>
</tbody>
</table>
</section>
<section id="communities-within-the-network" class="level2">
<h2 class="anchored" data-anchor-id="communities-within-the-network">Communities Within the Network</h2>
<div id="cell-9" class="cell" data-outputid="81d6fc3b-3e2a-4c13-d1d1-2a8b65b315da" data-execution_count="22">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>To find substructure inside the larger network, two community-detection algorithms were compared on 10%-node subgraph samples: Louvain modularity optimization and Girvan-Newman edge-betweenness partitioning. Louvain consistently produced tighter, larger communities across every sampled subgraph (modularity Q = 0.66 on one representative sample, versus Q = 0.25 for Girvan-Newman) and was adopted for the full analysis. Girvan-Newman turned out to be a poor fit for this particular network: because the graph is small-world, with an average shortest path of only 2.28, there are many alternate routes between any two artists, so no single edge acts as an obvious bridge for betweenness to detect.</p>
<p>Applying Louvain modularity to the full network, rather than a sample, surfaced 11 distinct communities at a modularity score of 0.60, a strong division for a network this dense. Community sizes range widely, from 948 artists in the largest to 62 in the smallest, which already hints that these clusters are not simply “genre buckets” of equal size.</p>
</section>
<section id="the-festivals-that-hold-it-together" class="level2">
<h2 class="anchored" data-anchor-id="the-festivals-that-hold-it-together">The Festivals That Hold It Together</h2>
<p>A natural follow-up question: how much of that structure is being driven by a handful of dominant festivals? Modularity clustering was re-run using only the artists who performed at Lollapalooza, Austin City Limits, and Coachella, arguably the three highest-profile U.S. festivals in the dataset.</p>
<div id="cell-12" class="cell" data-outputid="fabac1ba-7245-4593-e389-95d3ee959f0f" data-execution_count="26">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="how-far-does-the-reach-of-the-big-three-extend" class="level3">
<h3 class="anchored" data-anchor-id="how-far-does-the-reach-of-the-big-three-extend">How far does the reach of the big three extend?</h3>
<p>Artists who played Lollapalooza, Coachella, or Austin City Limits in 2023 also turned up in roughly 27 of the other 30 festivals in the dataset, domestic and international. No single community from this clustering was confined to just one of the three festivals, so the overlap looks less like three separate artist pools and more like a shared touring circuit that these festivals sit at the center of. A closer read of two of the resulting communities is suggestive without being conclusive: one skewed toward pop headliners, another toward rock and alternative acts, which points to genre as one organizing factor among several, alongside geography and booking relationships.</p>
</section>
</section>
<section id="testing-the-structure-with-link-prediction" class="level2">
<h2 class="anchored" data-anchor-id="testing-the-structure-with-link-prediction">Testing the Structure With Link Prediction</h2>
<p>Community structure is descriptive; it says the network is organized, not that the organization is useful. To test whether the structure carries real predictive signal, link prediction was framed around one smaller festival, Sunburn, and evaluated under three scenarios designed to avoid the leakage that would come from training and testing on the same festival’s edges.</p>
<p><strong>Case 1</strong> tried to predict links <em>within</em> Sunburn’s own lineup, using only past co-performance data. <strong>Case 2</strong> predicted links from Sunburn’s artists <em>out</em> to every other festival’s performers, with Sunburn’s own edges withheld from training. <strong>Case 3</strong> ran the same out-of-festival prediction, but kept the edges belonging to the three major U.S. festivals (Lollapalooza, Coachella, Austin City Limits) in the training graph.</p>
<div id="cell-16" class="cell" data-outputid="693f0749-0038-4cd5-b9b5-c54c3b49da4a" data-execution_count="36">
<div class="cell-output cell-output-stdout">
<pre><code>Predicted probabilities (first 5): [0.04959519 0.05129732 0.12272923 0.04458644 0.06143086]
Predicted labels (first 5): [0 0 0 0 0]

Precision: 0.8154
Recall: 0.1748
F1-score: 0.2879
AUC: 0.7125</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-7-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-17" class="cell" data-outputid="403f0907-46c6-4bab-effe-c9c146f65d77" data-execution_count="37">
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 800x600 with 0 Axes&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-8-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion matrix calculated and displayed.</code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Scenario</th>
<th>Precision</th>
<th>Recall</th>
<th>F1</th>
<th>AUC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Case 1: within-festival</td>
<td>0.008</td>
<td>0.966</td>
<td>0.015</td>
<td>0.833</td>
</tr>
<tr class="even">
<td>Case 2: cross-festival, majors removed</td>
<td>0.815</td>
<td>0.175</td>
<td>0.288</td>
<td>0.713</td>
</tr>
<tr class="odd">
<td>Case 3: cross-festival, majors retained</td>
<td>0.996</td>
<td>0.962</td>
<td>0.979</td>
<td>0.999</td>
</tr>
</tbody>
</table>
<p>The pattern across all three cases points the same direction. Case 1 collapsed on precision (0.008) despite near-perfect recall, because intra-festival connections are so sparse that almost any predicted pair is a false positive. Case 2, shown in the confusion matrix above, was more conservative: moderate precision (0.815) but recall low enough (0.175) that most real Sunburn-to-elsewhere connections went undetected. Case 3 is the standout: with the major festivals’ edges left in the training graph, the model predicted Sunburn’s external connections almost perfectly (F1 = 0.979, AUC = 0.999). The major festivals are acting as structural anchors, once the model can see how an artist relates to Lollapalooza, Coachella, or Austin City Limits, its connections to the rest of the network become highly predictable. Remove that anchor and prediction degrades sharply. That is strong evidence that a small set of festivals disproportionately shapes the topology of the entire touring circuit.</p>
</section>
<section id="does-the-music-explain-the-communities" class="level2">
<h2 class="anchored" data-anchor-id="does-the-music-explain-the-communities">Does the Music Explain the Communities?</h2>
<p>The second research question flips the first one around: given that Louvain found 11 communities in the network, are those communities separable by what the artists actually sound like, or by genre? If booking patterns tracked musical similarity, community membership should be at least somewhat predictable from Spotify’s audio features (danceability, energy, tempo, valence, and similar) and genre metadata.</p>
<div id="cell-20" class="cell" data-outputid="52b3fe86-9210-4d0d-d63b-b9bb47d26331">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Community_Label_Mod</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>948</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>514</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>382</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8</td>
<td>374</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>338</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>330</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>244</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>229</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7</td>
<td>202</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>106</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">9</td>
<td>62</td>
</tr>
</tbody>
</table>

</div><br><label><b>dtype:</b> int64</label>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Number of Artists in Community Data: 3729 Artists</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-9-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Four classifiers, logistic regression, a voting ensemble, random forest, and k-nearest neighbors, were trained to predict Louvain community membership from audio and genre features alone.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Logistic Regression</td>
<td>24.9%</td>
</tr>
<tr class="even">
<td>Voting Classifier</td>
<td>19.8%</td>
</tr>
<tr class="odd">
<td>Random Forest</td>
<td>18.1%</td>
</tr>
<tr class="even">
<td>KNN</td>
<td>15.6%</td>
</tr>
</tbody>
</table>
<p>None of the four came close to reliable classification; logistic regression’s 24.9% was the best of a weak field, against a naive baseline of roughly 9% for 11 balanced classes, real but modest signal. The likely explanation is homogeneity rather than randomness: every community, regardless of its position in the network, is dominated by EDM sub-genres and EDM-heavy festivals. Community 1, for instance, is built mostly from artists in minimal techno, hardstyle, drum-and-bass, dub, and house, who mainly performed at EDM-focused festivals like Tomorrowland and EDC, but also turn up at nearly every other festival in the dataset. When every community shares a similar genre mix, genre stops being a useful axis for telling them apart, even though it may still shape the network at a coarser level.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Structurally, the 2023 festival circuit behaves like a small-world network: short paths, dense local clustering, and a handful of major festivals, Lollapalooza, Austin City Limits, Coachella, acting as hubs that connect otherwise-separate regional and genre-based touring circuits. That structure is not just descriptive; it is predictive, link prediction anchored on those major festivals reconstructed a smaller festival’s outside connections with near-perfect accuracy. What the network’s structure does not explain is the music itself: the 11 communities Louvain found were not meaningfully separable by audio features or genre, which suggests that co-performance is driven less by how artists sound and more by relationships, geography, and the logistics of who tours where. The circuit runs on connections, and a small number of central festivals hold a disproportionate amount of the network together.</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<p>The dataset is a single-year (2023) snapshot, which rules out any analysis of how the network evolves year over year, and it is heavily skewed toward EDM festivals, which likely inflates the apparent lack of musical separability between communities. The network also lacks the business-side metadata, record labels, promoter and agency affiliations, radius clauses limiting how close together an artist can play, that plausibly explain co-performance patterns better than either network topology or musical similarity can. Extending the dataset across multiple years, and incorporating that business context, would be the natural next step for testing whether these findings generalize beyond 2023.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Hagan, D. (2019). How do the promoters of independent UK music festivals organise and implement events? <a href="https://repository.uwl.ac.uk/id/eprint/6608/">University of West London repository</a>.</li>
<li>Crossley, N., &amp; Emms, R. (2016). Mapping the Musical Universe: A blockmodel of UK Music Festivals, 2011-13. <a href="https://research.manchester.ac.uk/en/publications/mapping-the-musical-universe-a-blockmodel-of-uk-music-festivals-2/">Research Explorer, University of Manchester</a>.</li>
<li>Fairy, T. (2025). Data-Driven Talent Booking: Using audience insights to curate a high-demand festival lineup. <a href="https://www.ticketfairy.com/blog/data-driven-talent-booking-using-audience-insights-to-curate-a-high-demand-festival-lineup">Ticket Fairy Promoter Blog</a>.</li>
<li>Carrier, M. A. (2024). The antitrust case against Live Nation Entertainment. <em>Harvard Journal of Sports &amp; Entertainment Law</em>, 15, 2-3.</li>
<li>Lane, T. (n.d.). Defining unreasonable radius clauses for American music festivals. <a href="https://digitalcommons.law.seattleu.edu/sulr/vol42/iss3/13/">Seattle University School of Law Digital Commons</a>.</li>
<li>Van Der Hoeven, A., Behr, A., Hamilton, C., Mulder, M., &amp; Rozbicka, P. (2021). 1-2-3-4! Measuring the values of live music: methods, models and motivations. <em>Arts and the Market</em>, 11(2), 147-166. <a href="https://doi.org/10.1108/aam-09-2020-0041">doi:10.1108/aam-09-2020-0041</a>.</li>
<li>Spotify Tracks Dataset. <a href="https://huggingface.co/datasets/maharshipandya/spotify-tracks-dataset">Hugging Face</a>.</li>
</ul>
<p><em>Team: Shreya Gupta, Lunden Mandigo, Tyrone Pettygrue, Vaishnavi Venkataraghavan. Course: SI 608, University of Michigan.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>